[GS] New: Programming tutorial I
bitsandvolts/bitsandvolts.github.io pull request #43
Opened 2023-01-13 22:34 UTC by leboem

Info:
- Why do we need programming languages
- Interpreted vs compiled languages

Post checklist:

- [ ] YAML: permalink
- [ ] YAML: excerpt
- [ ] YAML: author
- [ ] YAML: toc label
- [ ] YAML: nav sidebar
- [ ] Ran Grammarly?
- [ ] Added some images?
- [ ] Ran local test?
- [ ] All links work?
- [ ] Date correct?
- [ ] Squashed commits?
- [ ] SEO?

2023-01-29 16:00 UTC, kyaso requested changes
Overall, solid post :)

2023-01-29 16:00 UTC, kyaso commented on _posts/2023-01-04-gs_00007_programming_I.md
> +  First part of our programming tutorial. Why do we need programming languages?
Maybe "tutorial series" ?

2023-01-29 16:00 UTC, kyaso commented on _posts/2023-01-04-gs_00007_programming_I.md
> +**program**? A program is a sequence of **instructions** that tells the computer
```suggestion
**program**? A program is essentially a sequence of **instructions** that tells the computer
```

2023-01-29 16:00 UTC, kyaso commented on _posts/2023-01-04-gs_00007_programming_I.md
> +instructions. One to load so-called **immediates** (=numbers) to a register (mv)
```suggestion
instructions. One to load so-called **immediates** (=numbers) into a register (called _mv_, for "move")
```

2023-01-29 16:00 UTC, kyaso commented on _posts/2023-01-04-gs_00007_programming_I.md
> +and one to add two registers (add). The so-called **Assembly Program**
```suggestion
and another one to add the values stored in two registers (_add_). Now, we can combine these instructions to create our first program:
```

2023-01-29 16:00 UTC, kyaso commented on _posts/2023-01-04-gs_00007_programming_I.md
> +languages like _C_ or _Python_ are invented for this purpose. So, your second
```suggestion
languages like _C_ or _Python_ were invented for this purpose. So, our second
```

2023-01-29 16:00 UTC, kyaso commented on _posts/2023-01-04-gs_00007_programming_I.md
> +directly, compiled languages are way faster. This will be enforced by several
"Because they are executed on the machine _directly_, compiled languages are usually way faster than their interpreted counterparts."

2023-01-29 16:00 UTC, kyaso commented on _posts/2023-01-04-gs_00007_programming_I.md
> +programming languages in general. Why do we need them? Why are there so many of
```suggestion
programming languages in general. What are they, and why do we need them? Why are there so many of
```

2023-01-29 16:00 UTC, kyaso commented on _posts/2023-01-04-gs_00007_programming_I.md
> +Registers are another way to store data. They are the fastest memory type, but
```suggestion
Registers are another way to store data, and are part of the processor. A register basically stores a single number. Registers are the fastest memory type our there, but
```

2023-01-29 16:00 UTC, kyaso commented on _posts/2023-01-04-gs_00007_programming_I.md
> +instructions. One to load so-called **immediates** (=numbers) to a register (mv)
I think it's not necessary to use the term "immediate" here. It's just a beginners post, so maybe simply saying "to load a number/value into a register" would do it. What do you say?

2023-01-29 16:00 UTC, kyaso commented on _posts/2023-01-04-gs_00007_programming_I.md
> +First, we load the immediates 1 and 2 to the registers r1 and r2. If we assume
"The above is an example of a so-called **Assembly program**. The **assembly language** is a programming language that consists of instructions which the processor can directly execute. In our example, we first load the values 1 and 2 into register..."

2023-01-29 16:00 UTC, kyaso commented on _posts/2023-01-04-gs_00007_programming_I.md
> +you can run it, the **Assembler** has to convert it to machine code. Let's
```suggestion
you can run it, a program called **Assembler** has to convert it to **machine code** (= 1s and 0s representation of the instructions). Let's
```

2023-01-29 16:00 UTC, kyaso commented on _posts/2023-01-04-gs_00007_programming_I.md
> +converted to 0001. Then, our first instruction would be 101000100001. This is
```suggestion
converted to 0001. Then, our first instruction could look like this: 101000100001. This is
```

2023-01-29 16:00 UTC, kyaso commented on _posts/2023-01-04-gs_00007_programming_I.md
> +then you want to use it on a different processor. But on that new processor your
"But what if on that new processor the instructions and registers are different?"

And maybe briefly touch upon that there are different ISAs.

2023-01-29 16:00 UTC, kyaso commented on _posts/2023-01-04-gs_00007_programming_I.md
> +reason to use programming languages is **Compatability**.
Maybe add something like this:

"Compatibility. So, we write code in one of these higher-level programming languages, and there are tools (that we will cover below) which ensure that our program can run on most processors."

2023-01-29 16:00 UTC, kyaso commented on _posts/2023-01-04-gs_00007_programming_I.md
> +case. So, depending on what you want to do, you'll choose a different language.
An example might illustrate the point better:

"use case, say a video game vs. a scientific simulation"

2023-01-29 16:00 UTC, kyaso commented on _posts/2023-01-04-gs_00007_programming_I.md
> +previous posts, then you already used an interpreter: your Linux shell. An
```suggestion
previous posts, then you already used an _interpreter_: your Linux shell. An
```

2023-01-29 16:00 UTC, kyaso commented on _posts/2023-01-04-gs_00007_programming_I.md
> +interpreter is a program itself that translates and executes commands one by
```suggestion
interpreter is a program itself that translates and executes commands given to it one by
```

2023-01-29 16:00 UTC, kyaso commented on _posts/2023-01-04-gs_00007_programming_I.md
> +Interpreted languages, however, are more flexible. For example, you can change
Not sure if this applies to all interpreted languages.

```suggestion
Interpreted languages, however, are more flexible. For example, in some interpreted languages, you can change
```

2023-01-29 16:00 UTC, kyaso commented on _posts/2023-01-04-gs_00007_programming_I.md
> +Interpreted languages, however, are more flexible. For example, you can change
Maybe give more advantages of interpreted ones, like faster to write code.

2023-03-05 22:57 UTC, leboem commented on _posts/2023-01-04-gs_00007_programming_I.md
> +then you want to use it on a different processor. But on that new processor your
Wouldn't that be too much detail? I mean to touch ISA

2023-03-05 23:02 UTC, leboem commented on _posts/2023-01-04-gs_00007_programming_I.md
> +reason to use programming languages is **Compatability**.
what tools do you mean?

2023-03-06 22:06 UTC, leboem commented on _posts/2023-01-04-gs_00007_programming_I.md
> +reason to use programming languages is **Compatability**.
I mean by tools

2023-03-08 21:29 UTC, kyaso commented on _posts/2023-01-04-gs_00007_programming_I.md
> +then you want to use it on a different processor. But on that new processor your
True. We can leave out the ISA point.

2023-03-08 21:30 UTC, kyaso commented on _posts/2023-01-04-gs_00007_programming_I.md
> +reason to use programming languages is **Compatability**.
I meant compilers. How about "software tools"?

2023-03-12 15:53 UTC, kyaso requested changes

2023-03-12 15:53 UTC, kyaso commented on _posts/2023-03-12-gs_00007_programming_I.md
> +faster to code interpreted languages.
```suggestion
faster to code in interpreted languages.
```

2023-03-12 15:53 UTC, kyaso commented on _posts/2023-03-12-gs_00007_programming_I.md
> +
Maybe add a quick transition into the Summary section.

2023-03-12 15:53 UTC, kyaso commented on _posts/2023-03-12-gs_00007_programming_I.md
> +Furthermore, you should know the difference between the following types:
```suggestion
Furthermore, you should know the difference between the following types of programming languages:
```

2023-03-12 15:53 UTC, kyaso commented on _posts/2023-03-12-gs_00007_programming_I.md
> +Next post, we will talk about common programming concepts. Hope to see you soon
```suggestion
In our next post, we will talk about common programming concepts. Hope to see you soon
```

2023-03-12 17:38 UTC, kyaso approved these changes

2023-03-12 17:41 UTC, merged